MimeKit/MimeMessage.cs, UnitTests/MimeMessageTests.cs
Hi,
When the following mail is parsed:
```
From: sender@domain.com
Date: Tue, 29 Aug 2017 09:45:39 +1000
Subject: This has no body, just a text attachment
Message-Id: <75SXBEJJ72U4.5KFFZ6J56L2T2@localhost.localdomain>
MIME-Version: 1.0
Content-Type: text/plain; name="Plain Text.txt"
Content-Disposition: attachment; filename="Plain Text.txt"
Content-Transfer-Encoding: 7bit
This is the text attachment
```
The Message.TextBody is set to the contents of the attachment, rather than being null as expected.
This is because the message doesn't have any body.  The fix is just to add a `&& !body.IsAttachment` to the condition in `MimeMessage.GetTextBody` on line 924.
I don't believe the RFC states you have to have a body, and email clients render this as expected - a blank message with a small text …
=> Don't set TextBody to contents of text attach when body undefined

MimeKit/Cryptography/BouncyCastleCertificateExtensions.cs
Hi,
when using revocation checking, the import for certain CRLs fails, because `GetCriticalExtensionOids()` inside `BouncyCastleCertificateExtensions.IsDelta` returns null for CRLs without any extensions.
This PR should fix this issue.
example: [crl without extensions](http://esignature.telekom.at/taca/crl/serialNumber_16_eSignature_Basic.crl)
=> Fixed X509Crl.IsDelta for CRLs without extensions

MimeKit/Cryptography/CryptographyContext.cs, MimeKit/Cryptography/KeyRetrievalResults.cs, MimeKit/Cryptography/OpenPgpContext.cs, MimeKit/Cryptography/PgpContext.cs, MimeKit/MimeKit.Net45.csproj, MimeKit/MimeKit.NetStandard.csproj
This too method needs to be public and virtual, in order for me to retrieve public keys, without relying upon `PublicKeyRingBundle`, which makes no sense, if user wants to store (millions potentially) of keys in database.
=> Making sure also public keys kan be retrieved without relying upon PublicKeyRingBundle

MimeKit/Cryptography/ArcSigner.cs, MimeKit/Cryptography/ArcVerifier.cs, UnitTests/Cryptography/ArcVerifierTests.cs
=> Added improved error reporting for ArcVerifier

MimeKit/MimeKit.csproj
Using the `System.Security.Cryptography.Pkcs` package, the `WindowsSecureMimeContext` and related classes can be used together with .NET Standard. This PR changes the csproj-File for MimeKit, including these classes and the package into the build for .NET Standard 2.0.
There might be some limitations when using this context on Linux / OS X, as the underlying `X509Store` used for storing / receiving [has some limitations](https://docs.microsoft.com/en-US/dotnet/standard/security/cross-platform-cryptography#x509store). However, at least for my use case (verifying / signing via S/MIME using the OS root certificates; as well as importing certs into the store and using them for en-/decryption), this works fine (using Debian Buster and Ubuntu Focal). 
We maybe should add a note concerning this …
=> Include WindowsSecureMimeContext in .NET Standard 2.x build

MimeKit/MimeKitLite.csproj
Removes Netstandard 1.x (all targets of which are no longer supported), and updates to the latest BouncyCastle version
=> Update to latest BouncyCastle and remove unsupported platforms (NS 1.x)

MimeKit/AttachmentCollection.cs, MimeKit/MimeKit.csproj
Hi, I don't know if you're looking for this kind of PR but I spotted the allocation when F12ing through the methods in Visual Studio.
A quick search for `new byte[` indicates that there are quite a few places in the library where the same pattern could be used e.g. `FilteredStream.Read`. Unfortunately I cannot currently dedicate the time to replace each instance so I thought I would introduce an example fix for this instance.
=> Don't allocate when adding attachments.

MimeKit/Cryptography/AuthenticationResults.cs, MimeKit/Cryptography/BouncyCastleCertificateExtensions.cs, MimeKit/Cryptography/OpenPgpContext.cs, MimeKit/Cryptography/OpenPgpDigitalCertificate.cs, MimeKit/DomainList.cs, MimeKit/Header.cs, MimeKit/MessageIdList.cs, MimeKit/MimeIterator.cs, MimeKit/MimeKit.csproj, MimeKit/MimeKitLite.csproj, MimeKit/ParameterList.cs, MimeKit/Utils/MimeUtils.cs, MimeKit/Utils/ParseUtils.cs, MimeKit/Utils/Rfc2047.cs, MimeKit/Utils/ValueStringBuilder.cs
This PR introduces and uses a ValueStringBuilder via [dotnet](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/System/Text/ValueStringBuilder.cs).
Under the hood, this uses a dynamically resizing array borrowed from ArrayPool to eliminate allocations. It can also accept stack allocated memory as an initial buffer (expanding to use borrowed heap memory, as needed). 
We must be careful to return the memory after use by calling ToString or Dispose, but otherwise -- this should be a nice net win for throughput.
=> Introduce ValueStringBuilder

MimeKit/Cryptography/ArcSigner.cs, MimeKit/Cryptography/AuthenticationResults.cs, MimeKit/Cryptography/DkimPublicKeyLocatorBase.cs, MimeKit/Cryptography/X509CertificateDatabase.cs, MimeKit/Header.cs, MimeKit/MimeIterator.cs, MimeKit/Multipart.cs, MimeKit/Utils/MimeUtils.cs, MimeKit/Utils/Rfc2047.cs, MimeKit/Utils/StringBuilderExtensions.cs, MimeKit/Utils/StringSplitter.cs, MimeKit/Utils/ValueStringBuilder.cs
- Introduces and uses a StringSplitter to avoid array (and array element) allocations
- Use ValueStringBuilder.AppendInvariant(value) to eliminate allocations appending span formattables on NET6+
- Eliminates various byte[] and string allocations
=> Reduce Allocations (take 2)

MimeKit/IO/Filters/BestEncodingFilter.cs
Ensures we account for endianness when reading uint. Ready for review.
=> Account for endianness when comparing uint

MimeKit/ContentDisposition.cs, MimeKit/Cryptography/AuthenticationResults.cs, MimeKit/Cryptography/BouncyCastleCertificateExtensions.cs, MimeKit/DomainList.cs, MimeKit/MimePart.cs, MimeKit/Utils/MimeUtils.cs, MimeKit/Utils/ValueStringBuilder.cs
- Use CultureInfo.InvariantCulture when formatting integers
- Eliminates various string allocations
=> Eliminate various string allocations

MimeKit/IO/MemoryBlockStream.cs, UnitTests/IO/MemoryBlockStreamTests.cs
`Math.Min` may return a negative value when the difference between
`length` and `position` is not in the range of `int`. It happens because
of the numeric conversion from `long` to `int`.
As a result, the `Read` method does not read a single byte.
This situation is possible when the length of the stream is greater than
`int.Max`.
=> Fix `MemoryBlockStream.Read` method.

MimeKit/Cryptography/SecureMimeContext.cs
The current implementation of the compression algorithm gets encoded
data using the `CmsCompressedData.GetEncoded` method:
https://github.com/bcgit/bc-csharp/blob/release-1.9.0/crypto/src/cms/CMSCompressedData.cs#L105
This method delegates real work to the `Asn1Encodable` class which
initializes one more temporary `MemoryStream` to get an array of
bytes:
https://github.com/bcgit/bc-csharp/blob/release-1.9.0/crypto/src/asn1/Asn1Encodable.cs#L30
Suggested solution writes encoded data directly into the stream.
=> Compression: improve memory usage. 

MimeKit/Header.cs, MimeKit/IO/FilteredStream.cs, MimeKit/IO/MeasuringStream.cs, MimeKit/IO/MemoryBlockStream.cs, MimeKit/MailboxAddress.cs, MimeKit/MimeEntity.cs, MimeKit/MimeReader.cs
Now that we've dropped net451, we can also remove some legacy logic.
=> Remove unused pragmas

Benchmarks/Benchmarks.csproj, MimeKit/MimeKit.csproj, MimeKit/MimeKitLite.csproj, nuget/MimeKit.nuspec, nuget/MimeKitLite.nuspec
.NET 5.0 reached end of life on May 10, 2022. This PR drops .NET5.0 target. Users that have not upgraded will pickup the .NETSTANDARD2.1 library instead.
=> Drop .NET5.0 support

MimeKit/Header.cs, MimeKit/InternetAddress.cs, MimeKit/Utils/ParseUtils.cs
Replaces a few mutable arrays with statically initialized readonly spans and removes an unused property.
@jstedfast ready for review.
=> Optimize sentinel checks

MimeKit/Cryptography/BouncyCastleSecureMimeContext.cs, MimeKit/MimeKit.csproj
See comment here for information: https://github.com/bcgit/bc-csharp/issues/516#issuecomment-1934781810 
Related: #998
=> Potentially fix CMS Data Envelope creation for ECC certificates

MimeKit/Cryptography/AsymmetricAlgorithmExtensions.cs
AsymmetricAlgorithmExtensionTests.TestDSACryptoServiceProvider can fail occasionally if the Y parameter happens to have enough leading zero bits.
=> DSAParameters.Y should be padded

MimeKit/Cryptography/BouncyCastleCertificateExtensions.cs, MimeKit/Cryptography/BouncyCastleSecureMimeContext.cs, MimeKit/Cryptography/SecureMimeDigitalSignature.cs
- use Asn1.Cms.Time for SigningTime attribute
- use X509Certificate.TbsCertificate property (instead of recoding)
- cleanup some obsolete TODOs
=> Improve several BC usages

MimeKit/Header.cs, MimeKit/HeaderId.cs, MimeKit/HeaderList.cs, MimeKit/HeaderListChangedEventArgs.cs, MimeKit/HeaderListCollection.cs
This pull request enables nullable reference types for (addresses #1067):
- `Header`
- `HeaderId`
- `HeaderList`
- `HeaderListChangedEventArgs`
- `HeaderListCollection`
=> Enable nullable reference types for some header related classes

README.md
I found no replacement. https://dotnetfoundation.org/community/ may be the best equivalent, but even there no real community forum can be found anymore?
Maybe they now use Discord or what? But that is not the same, IMHO. And not worth promoting in any case.
=> docs: remove .NET forum discussion link as it does not exist anymore

MimeKit/HeaderId.cs
This was totally confusing for me why there are two header IDs in MimeKit with the quite very same header. I even suspected a bug or that it is just a legacy API-compatibility thing (one being deprecated, though not stated?).
After some research it turns out, the header is actually defined. At least for the modern RFC3834 header the keywords are actually also defined by IANA: https://www.iana.org/assignments/auto-submitted-keywords/auto-submitted-keywords.xml (But you don't do mapping to an enum, so introducing this would change the API drastically and be a different/bigger task, so I thought for the code this may not be relevant.)
So to clarify this and ease searching around the web and decrease potential confusion for other developers, IMHO, it is a good idea to just directly point out …
=> Update HeaderId to clarify the difference between Autosubmitted and Auto-Submitted

MimeKit/MimeKit.csproj, MimeKit/MimeKitLite.csproj, nuget/MimeKit.nuspec, nuget/MimeKitLite.nuspec
NetStandard2.1 implicitly supports Span, so can exclude these explicit dependencies:
```
<PackageReference Include="System.Buffers" Version="4.5.1" />
<PackageReference Include="System.Memory" Version="4.5.5" />
```
This dependency is also no longer needed for MimeKit:
```
<PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
```
=> Reduce dependencies for NetStandard2.1

MimeKit/Cryptography/BouncyCastleCertificateExtensions.cs, MimeKit/Cryptography/X509KeyUsageFlags.cs
While implementing IX509CertificateDatabase and extending BouncyCastleSecureMimeContext I ran into a few internal methods I would like to use for consistency. This PR exposes those with code documentation.
I chose this crypto-abstratctions branch because I thought it might be the appropriate place but I could change the PR to the main branch if my changes are acceptable.
I have more PRs. I just want to ensure they are something you are OK with.
Future PR themes I have ready are:
Ability to find end certificate in IX509CertificateDatabase for signing and encryptiing with techniques other than Email. I work on a OS project called the [nhin-d](https://github.com/DirectProject/nhin-d) refered to as the Direct Project. It is a SMIME protocol where the public certificates are disoverable in DNS …
=> Allow easier implementation of IX509CertificateDatabase and BouncyCastleSecureMimeContext

UnitTests/Cryptography/AsymmetricAlgorithmExtensionTests.cs
Changed the RSA and DSA key size to 2048 in the Unit Tests.
=> Weak encryption: Insufficient key size

MimeKit/IO/MemoryBlockStream.cs, UnitTests/IO/MemoryBlockStreamTests.cs
This pull request add a unit test which checks that `MemoryBlockStream` correctly throws `ObjectDisposedException`. This was not the case for `MemoryBlockStream.ToArray` which is added in the second commit.
I found this while working on #1067 but opened a separate PR because strictly speaking this a behavioral change in public API.
=> Check if disposed in MemoryBlockStream.ToArray

MimeKit/IO/FilteredStream.cs, UnitTests/IO/FilteredStreamTests.cs
This pull request add a unit test which checks that `FilteredStream` correctly throws `ObjectDisposedException`. This was not the case for `Add`, `Remove`, and `Contains` which is added in the second commit.
I was uncertain whether it would make sense to add a `leaveOpen` parameter here too. It has not been necessary so far and following the .NET pattern introducing a parameter `bool leaveOpen = false` would be potentially dangerous behavior change. Therefore, I decided to just a comment that the source stream won't be disposed.
=> Check if disposed on FilteredStream filter manipulation

MimeKit/Cryptography/BouncyCastleSecureMimeContext.cs, MimeKit/Cryptography/X509Certificate2Extensions.cs, MimeKit/MimeKit.csproj, UnitTests/Cryptography/X509CertificateGenerator.cs, UnitTests/Cryptography/X509CrlGenerator.cs
- fix references to obsolete methods
- refactor some BC usages
=> Update to BouncyCastle.Cryptography 2.6.1
